#!/bin/sh -e

for prog in nghttp nghttpd nghttpx h2load; do
    src/$prog -h | ./help2rst.py -i doc/source/$prog.h2r > doc/source/$prog.1.rst
done

cd doc
make man

for prog in nghttp nghttpd nghttpx h2load; do
    cp build/man/$prog.1 $prog.1
done
